// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFeed = `-- name: AddFeed :one
INSERT INTO
  feeds (id, name, created_at, updated_at, url)
VALUES
  ($1, $2, $3, $4, $5)
RETURNING
  id, name, created_at, updated_at, url, last_fetched_at
`

type AddFeedParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Url       string
}

func (q *Queries) AddFeed(ctx context.Context, arg AddFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, addFeed,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Url,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.LastFetchedAt,
	)
	return i, err
}

const delFeed = `-- name: DelFeed :exec
DELETE FROM feeds
`

func (q *Queries) DelFeed(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, delFeed)
	return err
}

const getFeed = `-- name: GetFeed :many
SELECT
  id, name, created_at, updated_at, url, last_fetched_at
FROM
  feeds
`

func (q *Queries) GetFeed(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
SELECT
  feeds.id, feeds.name, feeds.created_at, feeds.updated_at, feeds.url, feeds.last_fetched_at
FROM
  users
  JOIN feed_follows ON users.id = feed_follows.user_id
  JOIN feeds ON feeds.id = feed_follows.feed_id
WHERE
  users.name = $1
`

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, name string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedIdByUrl = `-- name: GetFeedIdByUrl :one
SELECT
  id
FROM
  feeds
WHERE
  url = $1
`

func (q *Queries) GetFeedIdByUrl(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getFeedIdByUrl, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getNextToFetch = `-- name: GetNextToFetch :one
SELECT
  id, name, created_at, updated_at, url, last_fetched_at
FROM
  feeds
ORDER BY
  last_fetched_at ASC NULLS FIRST
LIMIT
  1
`

func (q *Queries) GetNextToFetch(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextToFetch)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.LastFetchedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
  id, created_at, updated_at, name
FROM
  users
WHERE
  id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const markFeedFetched = `-- name: MarkFeedFetched :one
UPDATE feeds
SET
  last_fetched_at = NOW(),
  updated_at = NOW()
WHERE
  id = $1
RETURNING
  id, name, created_at, updated_at, url, last_fetched_at
`

func (q *Queries) MarkFeedFetched(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markFeedFetched, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.LastFetchedAt,
	)
	return i, err
}
