// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chiprs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addChirp = `-- name: AddChirp :one
INSERT INTO
  chiprs (id, created_at, updated_at, body, user_id)
VALUES
  (
    gen_random_uuid(),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    $1,
    $2
  )
RETURNING
  id, created_at, updated_at, body, user_id
`

type AddChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) AddChirp(ctx context.Context, arg AddChirpParams) (Chipr, error) {
	row := q.db.QueryRowContext(ctx, addChirp, arg.Body, arg.UserID)
	var i Chipr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteChiprByID = `-- name: DeleteChiprByID :exec
DELETE FROM chiprs
WHERE
  id = $1
`

func (q *Queries) DeleteChiprByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChiprByID, id)
	return err
}

const getAllChirpAsc = `-- name: GetAllChirpAsc :many
SELECT
  id, created_at, updated_at, body, user_id
FROM
  chiprs
ORDER BY
  created_at ASC
`

func (q *Queries) GetAllChirpAsc(ctx context.Context) ([]Chipr, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirpAsc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chipr
	for rows.Next() {
		var i Chipr
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChiprByID = `-- name: GetChiprByID :one
SELECT
  id, created_at, updated_at, body, user_id
FROM
  chiprs
WHERE
  id = $1
`

func (q *Queries) GetChiprByID(ctx context.Context, id uuid.UUID) (Chipr, error) {
	row := q.db.QueryRowContext(ctx, getChiprByID, id)
	var i Chipr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
