// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const allUser = `-- name: AllUser :many
SELECT
  id, created_at, updated_at, email
FROM
  users
`

func (q *Queries) AllUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, allUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (id, created_at, updated_at, email)
VALUES
  (gen_random_uuid(), $1, $2, $3)
RETURNING
  id, created_at, updated_at, email
`

type CreateUserParams struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.CreatedAt, arg.UpdatedAt, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const delUser = `-- name: DelUser :exec
DELETE FROM users
`

func (q *Queries) DelUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, delUser)
	return err
}
